CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    order_id_formatted VARCHAR(100) NOT NULL UNIQUE,
    subtotal DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    final_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PLACED', -- PLACED, CONFIRMED, PREPARING, READY, COMPLETED, CANCELLED
    payment_method VARCHAR(50) NOT NULL, -- UPI, CARD, COUNTER_PAY
    payment_status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, PAID, FAILED, REFUNDED
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT, -- Nullable if product is hard deleted
    product_name VARCHAR(255) NOT NULL,
    product_image_url VARCHAR(512),
    quantity INT NOT NULL,
    unit_base_price DECIMAL(10, 2) NOT NULL,
    customization_total DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    unit_final_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

CREATE TABLE order_item_customizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL,
    customization_group_name VARCHAR(255) NOT NULL,
    customization_option_name VARCHAR(255) NOT NULL,
    additional_price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_oic_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    changed_by_id BIGINT, -- ID of admin or customer who changed it
    changed_by_type VARCHAR(50) NOT NULL, -- ADMIN, CUSTOMER, SYSTEM
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- Sequence for custom formatting: MOBILE_PREFIX-ORD-SEQ (e.g. 9876-ORD-0001001)
CREATE SEQUENCE order_number_seq START WITH 1001;
